# Ironhack Data Analytics Project2

## Barcelona citizens with ages +60

In [2]:
import pandas as pd

In [3]:
url_padro = "https://opendata-ajuntament.barcelona.cat/data/dataset/9e93c1db-118a-4520-99e6-b3b955c33758/resource/61d91b31-9ba9-45ca-9cc3-47bf99555b4b/download/2020_padro_edat_any_a_any_per_sexe.csv"

In [4]:
padro = pd.read_csv(url_padro)

In [5]:
padro

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Sexe,Edat_any_a_any,Nombre
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98
...,...,...,...,...,...,...,...,...
14741,2020,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,Home,100 anys i més,1
14742,2020,10,Sant Martí,70,el Besòs i el Maresme,Home,100 anys i més,1
14743,2020,10,Sant Martí,71,Provençals del Poblenou,Home,100 anys i més,0
14744,2020,10,Sant Martí,72,Sant Martí de Provençals,Home,100 anys i més,1
14745,2020,10,Sant Martí,73,la Verneda i la Pau,Home,100 anys i més,2

In [5]:
# Adding a key column to the data set

In [6]:
padro["key"] = range(1, len(padro) + 1)

In [12]:
padro.head()

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Sexe,Edat_any_a_any,Nombre,key
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5

In [13]:
padro.columns

Index(['Any', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'Sexe', 'Edat_any_a_any', 'Nombre', 'key'],
      dtype='object')

In [14]:
padro_columns = ['any', 'codi_districte', 'nom_districte', 'codi_barri', 'nom_barri',
       'sexe', 'edat', 'nombre', "key"]

In [15]:
padro.columns = padro_columns

In [16]:
padro.head()

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,edat,nombre,key
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5

In [17]:
years = pd.DataFrame(padro["edat"].str.split(" ", 1).tolist(),columns=["edats", "ref"])

In [18]:
years["key"] = range(1, len(years) + 1)

In [19]:
years

      edats         ref    key
0         0        anys      1
1         0        anys      2
2         0        anys      3
3         0        anys      4
4         0        anys      5
...     ...         ...    ...
14741   100  anys i més  14742
14742   100  anys i més  14743
14743   100  anys i més  14744
14744   100  anys i més  14745
14745   100  anys i més  14746

[14746 rows x 3 columns]

In [15]:
# Mergin both data sets with the new column for the ages

In [15]:
padro_merge = pd.merge(padro, years, on='key')

In [16]:
padro_merge.head()

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,edat,nombre,key,edats,ref
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1,0,anys
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2,0,anys
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3,0,anys
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4,0,anys
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5,0,anys

In [18]:
# Dropping unecessary columns

In [17]:
padro_merge.drop(["ref"], axis=1, inplace=True)

In [18]:
padro_merge.drop(["edat"], axis=1, inplace=True)

In [19]:
padro_merge.head()

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,nombre,key,edats
0,2020,1,Ciutat Vella,1,el Raval,Dona,203,1,0
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,59,2,0
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,36,3,0
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,59,4,0
4,2020,2,Eixample,5,el Fort Pienc,Dona,98,5,0

In [22]:
# Converting the object edats to int

In [20]:
padro_merge['edats'] = padro_merge.edats.astype(int)

#### Total Population by neightborhood

In [124]:
barri = padro_merge.groupby("nom_barri").sum()

In [125]:
new_barri = barri.reset_index()

In [126]:
new_barri

,nom_barri,any,codi_districte,codi_barri,nombre,key,edats
0,Baró de Viver,408040,1818,11716,2625,1493689,10100
1,Can Baró,408040,1414,6868,9331,1488841,10100
2,Can Peguera,408040,1616,9494,2234,1491467,10100
3,Canyelles,408040,1616,9898,6869,1491871,10100
4,Ciutat Meridiana,408040,1616,11110,11091,1493083,10100
...,...,...,...,...,...,...,...
68,la Vila Olímpica del Poblenou,408040,2020,13534,9385,1495507,10100
69,la Vila de Gràcia,408040,1212,6262,50926,1488235,10100
70,les Corts,408040,808,3838,46731,1485811,10100
71,les Roquetes,408040,1616,10100,16417,1492073,10100
72,les Tres Torres,408040,1010,4848,16617,1486821,10100

In [128]:
#Llista de barris amb nombre d´habitans
#pd.set_option('display.max_rows', None) to show whole dataset
totals_barri = new_barri[["nom_barri", "nombre",]]

In [26]:
totals_barri

                        nom_barri  nombre
0                   Baró de Viver    2625
1                        Can Baró    9331
2                     Can Peguera    2234
3                       Canyelles    6869
4                Ciutat Meridiana   11091
..                            ...     ...
68  la Vila Olímpica del Poblenou    9385
69              la Vila de Gràcia   50926
70                      les Corts   46731
71                   les Roquetes   16417
72                les Tres Torres   16617

[73 rows x 2 columns]

### Total Population by district

In [119]:
districte = padro_merge.groupby("nom_districte").sum()

In [117]:
new_districte = districte.reset_index()

In [29]:
#Llista de districtes amb nombre d´habitants

new_districte[["nom_districte", "nombre"]]

         nom_districte  nombre
0         Ciutat Vella  108331
1             Eixample  270694
2               Gràcia  123651
3       Horta-Guinardó  174799
4            Les Corts   82635
5           Nou Barris  174012
6          Sant Andreu  151976
7           Sant Martí  241691
8       Sants-Montjuïc  187584
9  Sarrià-Sant Gervasi  151157

In [30]:
total_districte = new_districte[["nom_districte", "nombre"]]

In [31]:
total_districte

         nom_districte  nombre
0         Ciutat Vella  108331
1             Eixample  270694
2               Gràcia  123651
3       Horta-Guinardó  174799
4            Les Corts   82635
5           Nou Barris  174012
6          Sant Andreu  151976
7           Sant Martí  241691
8       Sants-Montjuïc  187584
9  Sarrià-Sant Gervasi  151157

### Total population by age

In [32]:
mayor_60 = padro_merge[padro_merge["edats"] > 60]

In [33]:
total_60 = mayor_60.groupby("nom_districte")["nombre"].sum().sort_values()

In [34]:
total_60df = pd.DataFrame(total_60).reset_index()

In [35]:
total_60df

         nom_districte  nombre
0         Ciutat Vella   16837
1            Les Corts   25871
2               Gràcia   31981
3  Sarrià-Sant Gervasi   39266
4          Sant Andreu   40465
5       Sants-Montjuïc   46311
6           Nou Barris   46393
7       Horta-Guinardó   48322
8           Sant Martí   60499
9             Eixample   72092

In [36]:
percentage_60 = pd.merge(total_districte, total_60df, on='nom_districte')

In [37]:
percentage_60 = percentage_60.rename(columns = {"nombre_x":"poblacio_total",
                                                "nombre_y":"poblacio_+60",
                                                })

In [38]:
percentage_60["%_poblacion_+60"] = ((percentage_60["poblacio_+60"]/percentage_60["poblacio_total"])*100)

In [39]:
#percentage_60.drop(["percentage"], axis=1, inplace=True)

In [40]:
percentage_60.loc['Total']= percentage_60[["poblacio_total", "poblacio_+60"]].sum()

In [41]:
percentage_60["+60_%_total"] = (percentage_60["poblacio_+60"]/sum(percentage_60.drop("Total")["poblacio_total"]))*100

In [42]:
percentage_60.fillna("", inplace=True)

In [43]:
percentage_60

,nom_districte,poblacio_total,poblacio_+60,%_poblacion_+60,+60_%_total
0,Ciutat Vella,108331.0,16837.0,15.5422,1.010303
1,Eixample,270694.0,72092.0,26.6323,4.325875
2,Gràcia,123651.0,31981.0,25.8639,1.919017
3,Horta-Guinardó,174799.0,48322.0,27.6443,2.899558
4,Les Corts,82635.0,25871.0,31.3076,1.552387
5,Nou Barris,174012.0,46393.0,26.6608,2.783808
6,Sant Andreu,151976.0,40465.0,26.6259,2.428099
7,Sant Martí,241691.0,60499.0,25.0315,3.630238
8,Sants-Montjuïc,187584.0,46311.0,24.6881,2.778888
9,Sarrià-Sant Gervasi,151157.0,39266.0,25.977,2.356153
Total,,1666530.0,428037.0,,25.684326

In [49]:
percentage_60["poblacio_+60"].mean()

77824.90909090909

In [71]:
percentage_60["poblacio_total"].mean()

303005.45454545453

In [45]:
percentage_60.groupby("nom_districte")["poblacio_total"].max().sort_values(ascending=False)

nom_districte
                       1666530.0
Eixample                270694.0
Sant Martí              241691.0
Sants-Montjuïc          187584.0
Horta-Guinardó          174799.0
Nou Barris              174012.0
Sant Andreu             151976.0
Sarrià-Sant Gervasi     151157.0
Gràcia                  123651.0
Ciutat Vella            108331.0
Les Corts                82635.0
Name: poblacio_total, dtype: float64

In [46]:
percentage_60.groupby("nom_districte")["poblacio_+60"].max().sort_values(ascending=False)

nom_districte
                       428037.0
Eixample                72092.0
Sant Martí              60499.0
Horta-Guinardó          48322.0
Nou Barris              46393.0
Sants-Montjuïc          46311.0
Sant Andreu             40465.0
Sarrià-Sant Gervasi     39266.0
Gràcia                  31981.0
Les Corts               25871.0
Ciutat Vella            16837.0
Name: poblacio_+60, dtype: float64

In [77]:
percentage_60.groupby("nom_districte")["%_poblacion_+60"].max()

nom_districte

Ciutat Vella           15.5422
Eixample               26.6323
Gràcia                 25.8639
Horta-Guinardó         27.6443
Les Corts              31.3076
Nou Barris             26.6608
Sant Andreu            26.6259
Sant Martí             25.0315
Sants-Montjuïc         24.6881
Sarrià-Sant Gervasi     25.977
Name: %_poblacion_+60, dtype: object

In [76]:
percentage_60.groupby("nom_districte")["+60_%_total"].max()

nom_districte
                       25.684326
Ciutat Vella            1.010303
Eixample                4.325875
Gràcia                  1.919017
Horta-Guinardó          2.899558
Les Corts               1.552387
Nou Barris              2.783808
Sant Andreu             2.428099
Sant Martí              3.630238
Sants-Montjuïc          2.778888
Sarrià-Sant Gervasi     2.356153
Name: +60_%_total, dtype: float64

### Population Density

In [79]:
pop_url = "https://opendata-ajuntament.barcelona.cat/data/dataset/b7ba32eb-806e-4c9c-b0b1-9bab387fe501/resource/08c88565-5b50-47d1-8234-6d3dd2da4c58/download/2019_densitat.csv"

In [80]:
density = pd.read_csv(pop_url)

In [81]:
density.head()

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Població,Superfície (ha),Superfície Residencial (ha),Densitat (hab/ha),Densitat neta (hab/ha)
0,2019,1,Ciutat Vella,1,el Raval,47353,110.0,49.6,430,955
1,2019,1,Ciutat Vella,2,el Barri Gòtic,18629,81.6,34.1,228,546
2,2019,1,Ciutat Vella,3,la Barceloneta,14857,109.5,13.5,136,1097
3,2019,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",22590,111.0,32.4,204,697
4,2019,2,Eixample,5,el Fort Pienc,32349,92.9,33.6,348,962

In [82]:
lower_names = [i.lower() for i in density.columns]

In [83]:
density.columns = lower_names

In [84]:
district_density =  density.groupby("nom_districte").sum().reset_index()

In [85]:
district_density

,nom_districte,any,codi_districte,codi_barri,població,superfície (ha),superfície residencial (ha),densitat (hab/ha),densitat neta (hab/ha)
0,Ciutat Vella,8076,4,10,103429,412.1,129.6,998,3295
1,Eixample,12114,12,45,265910,746.4,372.1,2300,4796
2,Gràcia,10095,30,150,121798,422.4,202.4,1461,3118
3,Horta-Guinardó,22209,77,418,171495,1191.9,289.9,2087,6423
4,Les Corts,6057,12,60,81974,601.0,177.9,496,1617
5,Nou Barris,26247,104,650,170669,805.1,232.7,3439,8914
6,Sant Andreu,14133,63,420,149821,658.9,190.5,1795,5476
7,Sant Martí,20190,100,685,238315,1038.7,288.6,2487,8526
8,Sants-Montjuïc,16152,24,116,184091,2267.7,251.5,2377,6116
9,Sarrià-Sant Gervasi,12114,30,147,149260,1991.5,610.9,1047,2043

In [86]:
real_pop = new_districte[["nom_districte", "nombre"]]

In [87]:
real_density = pd.merge(district_density, real_pop, on='nom_districte')

In [88]:
real_density

,nom_districte,any,codi_districte,codi_barri,població,superfície (ha),superfície residencial (ha),densitat (hab/ha),densitat neta (hab/ha),nombre
0,Ciutat Vella,8076,4,10,103429,412.1,129.6,998,3295,108331
1,Eixample,12114,12,45,265910,746.4,372.1,2300,4796,270694
2,Gràcia,10095,30,150,121798,422.4,202.4,1461,3118,123651
3,Horta-Guinardó,22209,77,418,171495,1191.9,289.9,2087,6423,174799
4,Les Corts,6057,12,60,81974,601.0,177.9,496,1617,82635
5,Nou Barris,26247,104,650,170669,805.1,232.7,3439,8914,174012
6,Sant Andreu,14133,63,420,149821,658.9,190.5,1795,5476,151976
7,Sant Martí,20190,100,685,238315,1038.7,288.6,2487,8526,241691
8,Sants-Montjuïc,16152,24,116,184091,2267.7,251.5,2377,6116,187584
9,Sarrià-Sant Gervasi,12114,30,147,149260,1991.5,610.9,1047,2043,151157

In [89]:
pop_2020 = real_density.drop(["població"], axis=1)

In [90]:
pop_2020['Km2'] = pop_2020["superfície (ha)"] * 0.01

In [91]:
pop_2020["density"] = (pop_2020["nombre"]/pop_2020["Km2"]).round()

In [92]:
pop_2020.loc['Total']= pop_2020[["superfície (ha)", "superfície residencial (ha)", "nombre", "Km2", "density"]].sum()

In [93]:
pop_2020.drop(["densitat neta (hab/ha)"], axis=1, inplace=True)

In [94]:
pop_2020.drop(["densitat (hab/ha)"], axis=1, inplace=True)

In [95]:
pop_2020.drop(["codi_districte", "codi_barri", "any",], axis=1, inplace=True)

In [96]:
pop_2020.fillna("", inplace=True)

In [97]:
pop_2020

,nom_districte,superfície (ha),superfície residencial (ha),nombre,Km2,density
0,Ciutat Vella,412.1,129.6,108331.0,4.121,26288.0
1,Eixample,746.4,372.1,270694.0,7.464,36267.0
2,Gràcia,422.4,202.4,123651.0,4.224,29273.0
3,Horta-Guinardó,1191.9,289.9,174799.0,11.919,14666.0
4,Les Corts,601.0,177.9,82635.0,6.010,13750.0
5,Nou Barris,805.1,232.7,174012.0,8.051,21614.0
6,Sant Andreu,658.9,190.5,151976.0,6.589,23065.0
7,Sant Martí,1038.7,288.6,241691.0,10.387,23269.0
8,Sants-Montjuïc,2267.7,251.5,187584.0,22.677,8272.0
9,Sarrià-Sant Gervasi,1991.5,610.9,151157.0,19.915,7590.0
Total,,10135.7,2746.1,1666530.0,101.357,204054.0

In [98]:
pop_2020["poblacio_+60"] = percentage_60["poblacio_+60"]

In [99]:
pop_2020

,nom_districte,superfície (ha),superfície residencial (ha),nombre,Km2,density,poblacio_+60
0,Ciutat Vella,412.1,129.6,108331.0,4.121,26288.0,16837.0
1,Eixample,746.4,372.1,270694.0,7.464,36267.0,72092.0
2,Gràcia,422.4,202.4,123651.0,4.224,29273.0,31981.0
3,Horta-Guinardó,1191.9,289.9,174799.0,11.919,14666.0,48322.0
4,Les Corts,601.0,177.9,82635.0,6.010,13750.0,25871.0
5,Nou Barris,805.1,232.7,174012.0,8.051,21614.0,46393.0
6,Sant Andreu,658.9,190.5,151976.0,6.589,23065.0,40465.0
7,Sant Martí,1038.7,288.6,241691.0,10.387,23269.0,60499.0
8,Sants-Montjuïc,2267.7,251.5,187584.0,22.677,8272.0,46311.0
9,Sarrià-Sant Gervasi,1991.5,610.9,151157.0,19.915,7590.0,39266.0
Total,,10135.7,2746.1,1666530.0,101.357,204054.0,428037.0

In [100]:
pop_2020["%_poblacion_+60"] = percentage_60["%_poblacion_+60"]

In [101]:
pop_2020["+60_%_total"] = percentage_60["+60_%_total"]

In [102]:
pop_2020

,nom_districte,superfície (ha),superfície residencial (ha),nombre,Km2,density,poblacio_+60,%_poblacion_+60,+60_%_total
0,Ciutat Vella,412.1,129.6,108331.0,4.121,26288.0,16837.0,15.5422,1.010303
1,Eixample,746.4,372.1,270694.0,7.464,36267.0,72092.0,26.6323,4.325875
2,Gràcia,422.4,202.4,123651.0,4.224,29273.0,31981.0,25.8639,1.919017
3,Horta-Guinardó,1191.9,289.9,174799.0,11.919,14666.0,48322.0,27.6443,2.899558
4,Les Corts,601.0,177.9,82635.0,6.010,13750.0,25871.0,31.3076,1.552387
5,Nou Barris,805.1,232.7,174012.0,8.051,21614.0,46393.0,26.6608,2.783808
6,Sant Andreu,658.9,190.5,151976.0,6.589,23065.0,40465.0,26.6259,2.428099
7,Sant Martí,1038.7,288.6,241691.0,10.387,23269.0,60499.0,25.0315,3.630238
8,Sants-Montjuïc,2267.7,251.5,187584.0,22.677,8272.0,46311.0,24.6881,2.778888
9,Sarrià-Sant Gervasi,1991.5,610.9,151157.0,19.915,7590.0,39266.0,25.977,2.356153
Total,,10135.7,2746.1,1666530.0,101.357,204054.0,428037.0,,25.684326

In [113]:
pop_2020.sort_values(["poblacio_+60"], ascending=False).drop("Total").reset_index()

,index,nom_districte,superfície (ha),superfície residencial (ha),nombre,Km2,density,poblacio_+60,%_poblacion_+60,+60_%_total
0,1,Eixample,746.4,372.1,270694.0,7.464,36267.0,72092.0,26.6323,4.325875
1,7,Sant Martí,1038.7,288.6,241691.0,10.387,23269.0,60499.0,25.0315,3.630238
2,3,Horta-Guinardó,1191.9,289.9,174799.0,11.919,14666.0,48322.0,27.6443,2.899558
3,5,Nou Barris,805.1,232.7,174012.0,8.051,21614.0,46393.0,26.6608,2.783808
4,8,Sants-Montjuïc,2267.7,251.5,187584.0,22.677,8272.0,46311.0,24.6881,2.778888
5,6,Sant Andreu,658.9,190.5,151976.0,6.589,23065.0,40465.0,26.6259,2.428099
6,9,Sarrià-Sant Gervasi,1991.5,610.9,151157.0,19.915,7590.0,39266.0,25.977,2.356153
7,2,Gràcia,422.4,202.4,123651.0,4.224,29273.0,31981.0,25.8639,1.919017
8,4,Les Corts,601.0,177.9,82635.0,6.010,13750.0,25871.0,31.3076,1.552387
9,0,Ciutat Vella,412.1,129.6,108331.0,4.121,26288.0,16837.0,15.5422,1.010303

In [137]:
pop_2020["%_total_hab"] = (pop_2020["nombre"]/sum(pop_2020.drop("Total")["nombre"]))*100

In [138]:
pop_2020

,nom_districte,superfície (ha),superfície residencial (ha),nombre,Km2,density,poblacio_+60,%_poblacion_+60,+60_%_total,%_total_hab
0,Ciutat Vella,412.1,129.6,108331.0,4.121,26288.0,16837.0,15.5422,1.010303,6.500393
1,Eixample,746.4,372.1,270694.0,7.464,36267.0,72092.0,26.6323,4.325875,16.242972
2,Gràcia,422.4,202.4,123651.0,4.224,29273.0,31981.0,25.8639,1.919017,7.419668
3,Horta-Guinardó,1191.9,289.9,174799.0,11.919,14666.0,48322.0,27.6443,2.899558,10.488800
4,Les Corts,601.0,177.9,82635.0,6.010,13750.0,25871.0,31.3076,1.552387,4.958507
5,Nou Barris,805.1,232.7,174012.0,8.051,21614.0,46393.0,26.6608,2.783808,10.441576
6,Sant Andreu,658.9,190.5,151976.0,6.589,23065.0,40465.0,26.6259,2.428099,9.119308
7,Sant Martí,1038.7,288.6,241691.0,10.387,23269.0,60499.0,25.0315,3.630238,14.502649
8,Sants-Montjuïc,2267.7,251.5,187584.0,22.677,8272.0,46311.0,24.6881,2.778888,11.255963
9,Sarrià-Sant Gervasi,1991.5,610.9,151157.0,19.915,7590.0,39266.0,25.977,2.356153,9.070164
Total,,10135.7,2746.1,1666530.0,101.357,204054.0,428037.0,,25.684326,100.000000

In [139]:
pop_2020["%_total_density"] = (pop_2020["density"]/sum(pop_2020.drop("Total")["density"]))*100

In [140]:
pop_2020

,nom_districte,superfície (ha),superfície residencial (ha),nombre,Km2,density,poblacio_+60,%_poblacion_+60,+60_%_total,%_total_hab,%_total_density
0,Ciutat Vella,412.1,129.6,108331.0,4.121,26288.0,16837.0,15.5422,1.010303,6.500393,12.882864
1,Eixample,746.4,372.1,270694.0,7.464,36267.0,72092.0,26.6323,4.325875,16.242972,17.773236
2,Gràcia,422.4,202.4,123651.0,4.224,29273.0,31981.0,25.8639,1.919017,7.419668,14.345712
3,Horta-Guinardó,1191.9,289.9,174799.0,11.919,14666.0,48322.0,27.6443,2.899558,10.488800,7.187313
4,Les Corts,601.0,177.9,82635.0,6.010,13750.0,25871.0,31.3076,1.552387,4.958507,6.738412
5,Nou Barris,805.1,232.7,174012.0,8.051,21614.0,46393.0,26.6608,2.783808,10.441576,10.592294
6,Sant Andreu,658.9,190.5,151976.0,6.589,23065.0,40465.0,26.6259,2.428099,9.119308,11.303380
7,Sant Martí,1038.7,288.6,241691.0,10.387,23269.0,60499.0,25.0315,3.630238,14.502649,11.403354
8,Sants-Montjuïc,2267.7,251.5,187584.0,22.677,8272.0,46311.0,24.6881,2.778888,11.255963,4.053829
9,Sarrià-Sant Gervasi,1991.5,610.9,151157.0,19.915,7590.0,39266.0,25.977,2.356153,9.070164,3.719604
Total,,10135.7,2746.1,1666530.0,101.357,204054.0,428037.0,,25.684326,100.000000,100.000000