# Ironhack Data Analytics Project2

## Barcelona citizens

In [2]:
import pandas as pd

In [3]:
url_citiziens = "https://opendata-ajuntament.barcelona.cat/data/dataset/9e93c1db-118a-4520-99e6-b3b955c33758/resource/61d91b31-9ba9-45ca-9cc3-47bf99555b4b/download/2020_padro_edat_any_a_any_per_sexe.csv"

In [4]:
citiziens_bcn_pd = pd.read_csv(url_citiziens)

In [5]:
# Adding a key column to the data set

In [6]:
citiziens_bcn_pd["index"] = range(1, len(citiziens_bcn_pd) + 1)

In [7]:
citiziens_bcn_pd.head()

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Sexe,Edat_any_a_any,Nombre,index
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5

In [8]:
citiziens_bcn_pd.columns

Index(['Any', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'Sexe', 'Edat_any_a_any', 'Nombre', 'index'],
      dtype='object')

In [9]:
citiziens_bcn_pd_columns = ['any', 'codi_districte', 'nom_districte', 'codi_barri', 'nom_barri',
       'sexe', 'edat', 'num_habitants', "index"]

In [10]:
citiziens_bcn_pd.columns = citiziens_bcn_pd_columns

In [11]:
citiziens_bcn_pd.head()

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,edat,num_habitants,index
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5

In [12]:
years = pd.DataFrame(citiziens_bcn_pd["edat"].str.split(" ", 1).tolist(),columns=["edats", "ref"])

In [13]:
years["index"] = range(1, len(years) + 1)

In [14]:
# Mergin both data sets with the new column for the ages

In [15]:
citiziens_bcn_pd_merge = pd.merge(citiziens_bcn_pd, years, on='index')

In [16]:
citiziens_bcn_pd_merge.head()

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,edat,num_habitants,index,edats,ref
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1,0,anys
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2,0,anys
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3,0,anys
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4,0,anys
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5,0,anys

In [17]:
# Dropping unecessary columns

In [18]:
citiziens_bcn_pd_merge.drop(["ref"], axis=1, inplace=True)

In [19]:
citiziens_bcn_pd_merge.head()

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,edat,num_habitants,index,edats
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1,0
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2,0
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3,0
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4,0
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5,0

In [20]:
# Converting the object edats to int

In [21]:
citiziens_bcn_pd_merge['edats'] = citiziens_bcn_pd_merge.edats.astype(int)

#### Total Population by neightborhood

In [22]:
barri = citiziens_bcn_pd_merge.groupby("nom_barri").sum()

In [23]:
new_barri = barri.reset_index()

In [24]:
new_barri.head()

,nom_barri,any,codi_districte,codi_barri,num_habitants,index,edats
0,Baró de Viver,408040,1818,11716,2625,1493689,10100
1,Can Baró,408040,1414,6868,9331,1488841,10100
2,Can Peguera,408040,1616,9494,2234,1491467,10100
3,Canyelles,408040,1616,9898,6869,1491871,10100
4,Ciutat Meridiana,408040,1616,11110,11091,1493083,10100

In [25]:
#Llista de barris amb nombre d´habitans

new_barri[["nom_barri", "num_habitants"]]

                                       nom_barri  num_habitants
0                                  Baró de Viver           2625
1                                       Can Baró           9331
2                                    Can Peguera           2234
3                                      Canyelles           6869
4                               Ciutat Meridiana          11091
5   Diagonal Mar i el Front Marítim del Poblenou          13526
6                                          Horta          28363
7                                    Hostafrancs          16203
8                                        Montbau           5225
9                                          Navas          22457
10                                     Pedralbes          11936
11                                         Porta          27813
12                       Provençals del Poblenou          21523
13                                   Sant Andreu          58508
14                                   Sant Antoni          38906
15                      Sant Genís dels Agudells           7538
16                        Sant Gervasi - Galvany          47915
17                    Sant Gervasi - la Bonanova          26245
18                      Sant Martí de Provençals          26168
19         Sant Pere, Santa Caterina i la Ribera          23241
20                                         Sants          43763
21                                 Sants - Badal          24938
22                                        Sarrià          25242
23                                    Torre Baró           2925
24                                      Vallbona           1421
25                     Vallcarca i els Penitents          16147
26         Vallvidrera, el Tibidabo i les Planes           4710
27                                        Verdun          12798
28                 Vilapicina i la Torre Llobeta          26083
29                              el Baix Guinardó          26180
..                                           ...            ...
43                                   el Poblenou          34432
44                          el Putxet i el Farró          30428
45                                      el Raval          48263
46                           el Turó de la Peira          16269
47               l'Antiga Esquerra de l'Eixample          43228
48                                la Barceloneta          15112
49                                    la Bordeta          19567
50                                      la Clota            709
51                        la Dreta de l'Eixample          44325
52                          la Font d'en Fargues           9544
53                         la Font de la Guatlla          10377
54                                  la Guineueta          15420
55                             la Marina de Port          31352
56                    la Marina del Prat Vermell           1227
57                    la Maternitat i Sant Ramon          23968
58                la Nova Esquerra de l'Eixample          58621
59                                la Prosperitat          27003
60                            la Sagrada Família          52245
61                                    la Sagrera          29521
62                                      la Salut          13478
63                                  la Teixonera          11927
64                              la Trinitat Nova           7669
65                             la Trinitat Vella          10487
66                              la Vall d'Hebron           5886
67                           la Verneda i la Pau          28878
68                 la Vila Olímpica del Poblenou           9385
69                             la Vila de Gràcia          50926
70                                     les Corts          46731
71                                  les Roquetes          16417
72                               les Tres Torres          16617

[73 rows x 2 columns]

### Total Population by district

In [99]:
districte = citiziens_bcn_pd_merge.groupby(["nom_districte"]).sum()

In [100]:
new_districte = districte.reset_index()

In [101]:
#Llista de districtes amb nombre d´habitants

new_districte[["nom_districte","num_habitants"]]

         nom_districte  num_habitants
0         Ciutat Vella         108331
1             Eixample         270694
2               Gràcia         123651
3       Horta-Guinardó         174799
4            Les Corts          82635
5           Nou Barris         174012
6          Sant Andreu         151976
7           Sant Martí         241691
8       Sants-Montjuïc         187584
9  Sarrià-Sant Gervasi         151157

### Total population by age between 18 and 31

In [102]:
citiziens_bcn_pd_merge.head(5)

,any,codi_districte,nom_districte,codi_barri,nom_barri,sexe,edat,num_habitants,index,edats
0,2020,1,Ciutat Vella,1,el Raval,Dona,0 anys,203,1,0
1,2020,1,Ciutat Vella,2,el Barri Gòtic,Dona,0 anys,59,2,0
2,2020,1,Ciutat Vella,3,la Barceloneta,Dona,0 anys,36,3,0
3,2020,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Dona,0 anys,59,4,0
4,2020,2,Eixample,5,el Fort Pienc,Dona,0 anys,98,5,0

In [103]:
youngest = citiziens_bcn_pd_merge[(citiziens_bcn_pd_merge["edats"] >= 18) & (citiziens_bcn_pd_merge["edats"] <= 32) ]

### Número de joves per districte

In [104]:
frec_youngest = youngest.groupby(['nom_districte'])['num_habitants'].sum().sort_values(ascending=False)
youngest_df = pd.DataFrame(data = frec_youngest).reset_index()
#youngest_df_frec.head()
#Merge de la taula total habitants x districte versus total habitant entre 18 y 32
percentatge_18_32= pd.merge(new_districte[[ 'nom_districte',"num_habitants",]], youngest_df, on='nom_districte')
#percentatge_18_32.drop('nom_barri_x',axis=1, inplace=True)

In [105]:
percentatge_18_32 = percentatge_18_32.rename(columns={'num_habitants_x':'poblacio_total', 'num_habitants_y':'poblacio_[18-32]' })

#% del num de joves en un barri
percentatge_18_32['%_barris[18-32]'] = ((percentatge_18_32["poblacio_[18-32]"]/percentatge_18_32["poblacio_total"])*100).round()
#% del num de jove sobre el total de poblacio en el mateix barri
percentatge_18_32['%_barris[Joves/Total]'] = (percentatge_18_32["poblacio_[18-32]"]/sum(percentatge_18_32["poblacio_total"]))*100

percentatge_18_32

,nom_districte,poblacio_total,poblacio_[18-32],%_barris[18-32],%_barris[Joves/Total]
0,Ciutat Vella,108331,31577,29.0,1.894775
1,Eixample,270694,56060,21.0,3.363876
2,Gràcia,123651,23171,19.0,1.390374
3,Horta-Guinardó,174799,29468,17.0,1.768225
4,Les Corts,82635,13871,17.0,0.832328
5,Nou Barris,174012,29945,17.0,1.796847
6,Sant Andreu,151976,24594,16.0,1.475761
7,Sant Martí,241691,40870,17.0,2.452401
8,Sants-Montjuïc,187584,36546,19.0,2.192940
9,Sarrià-Sant Gervasi,151157,26639,18.0,1.598471

In [106]:
#Sumar total i treure els NA
percentatge_18_32.loc['Total'] = percentatge_18_32[['poblacio_total','poblacio_[18-32]','%_barris[18-32]', '%_barris[Joves/Total]' ]].sum()
percentatge_18_32.fillna('',inplace=True)
percentatge_18_32.head()

,nom_districte,poblacio_total,poblacio_[18-32],%_barris[18-32],%_barris[Joves/Total]
0,Ciutat Vella,108331.0,31577.0,29.0,1.894775
1,Eixample,270694.0,56060.0,21.0,3.363876
2,Gràcia,123651.0,23171.0,19.0,1.390374
3,Horta-Guinardó,174799.0,29468.0,17.0,1.768225
4,Les Corts,82635.0,13871.0,17.0,0.832328

### Density inmigrants

In [34]:
url_inmigrants = 'https://opendata-ajuntament.barcelona.cat/data/dataset/653e65cc-9bda-4d89-9701-033998379066/resource/816f6f82-0598-4ff4-a4b8-1be4c898fd24/download/2019_immigrants_nacionalitats.csv'

In [35]:
inmigrants_bcn_pd = pd.read_csv(url_inmigrants)
sum(inmigrants_bcn_pd['Nombre'])

115308

In [36]:
inmigrants_estrangers = inmigrants_bcn_pd[inmigrants_bcn_pd['Nacionalitats'] != 'Espanyola'].reset_index()
frec_df = inmigrants_estrangers.groupby(['Nom_Districte', 'Nom_Barri'])['Nombre'].sum().sort_values(ascending=False)
inmigrants_df_frec = pd.DataFrame(data = frec_df).reset_index()
sum(inmigrants_df_frec['Nombre'])

81673

In [37]:

inmigrants_df_frec['%_barris'] = round((inmigrants_df_frec["Nombre"]/sum(inmigrants_bcn_pd['Nombre'])*100),2)

inmigrants_df_frec.head()

    Nom_Districte                       Nom_Barri  Nombre  %_barris
0    Ciutat Vella                        el Raval    5012      4.35
1    Ciutat Vella                  el Barri Gòtic    4220      3.66
2  Sants-Montjuïc                           Sants    3116      2.70
3        Eixample              la Sagrada Família    2960      2.57
4        Eixample  la Nova Esquerra de l'Eixample    2955      2.56

In [39]:
url_inm = 'https://opendata-ajuntament.barcelona.cat/data/dataset/9e7d4905-914a-4ee6-9992-9bdecf1c018d/resource/04ceda77-ceb5-4ae7-ad64-20a4cb4f94f0/download/2019_taxa_immigracio.csv'
inm_df = pd.read_csv(url_inm)
inm_df = inm_df.groupby(['Nom_Districte'])['Nombre'].sum().sort_values(ascending=False)
inm_df_filtered = pd.DataFrame(data = inm_df).reset_index()
inm_df_filtered.loc[:,'Nombre'] /= 10
inm_df_filtered.rename(columns={'Nombre':'%_inmg_total'})

         Nom_Districte  %_inmg_total
0           Nou Barris         72.21
1         Ciutat Vella         64.27
2       Horta-Guinardó         59.84
3           Sant Martí         59.69
4       Sants-Montjuïc         59.51
5             Eixample         50.83
6          Sant Andreu         39.83
7               Gràcia         30.70
8  Sarrià-Sant Gervasi         29.48
9            Les Corts         18.37